---
title: "Spotify-Musicology"
author: "Aaron Kuin"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(spotifyr)
library(ggplot2)
library(dplyr)
library(plotly)
library(compmus)
```

Introduction
==============================================================================

Text-Box {data-width=700}
-------------------------------------------------------------------------------
My corpus is a combination of songs from both very popular and less popular artists. What is most important about this corpus is that all of the songs in this corpus were not written by their respective artists, but instead written by (several) ghostwriters. Think about artists such as Jay-z who wrote for dr. Dre and Snoop dogg, Elvis Presley who has not written a single song himself and even artists such as Frank Sinatra. Personally I think it is very interesting to look into the impact different artists/performers have on similar song. Ofcourse not all songs are the same, but for the sake of this research I think its ok to assume that a songwriter writes somewhat similar songs. From this we can start looking at the differences between different artists who perform songs from the same ghostwriter. This corpus was chosen with a few certain groups in mind, most importantantly writers, however it will also be possible to distinguish between different time periods as songs from the 50s will be in this corpus, as well as songs from the recent years. What will be important to keep in mind is that different ghostwriters will be used in this corpus and I expect massive differences between different ghostwriters. For specific songs to analyse I think it would be good to compare 2 songs per ghostwriter in the corpus.

Visualisations
==============================================================================

Plot 1 {data-width=400}
---------------------------------------------------------------------------
### Popularity of writers
```{r}
par(mar = c(4, 4, .1, .1))
OG <- get_playlist_audio_features("", "2WJJSs9WY3zaOPKHNKHAMK")
Ghosts <- get_playlist_audio_features("", "1q8Tw6AvQ3K17zOhjZ8D0B")
jointdataset <- rbind(OG, Ghosts)
ggplot(jointdataset, aes(x = track.popularity, y = playlist_name)) + geom_point()
```

Plot 2 {data-width=400}
---------------------------------------------------------------------------

### Overview of energy, tempo and danceability
```{r}
plot_ly(jointdataset, x=~tempo, y=~danceability, z=~energy, type="scatter3d", mode="markers", color =~playlist_name, size=1)

```

Row {data-width=200}
-----------------------------------------------------------------------

### Amount of songs

```{r}
valueBox(93, icon = "fa-microphone-lines")
```

### Amount of albums

```{r}
valueBox(15, icon = "fa-album-collection", color = "brown")
```

### Amount of artists

```{r}
valueBox(2, 
         icon = "fa-person",
         color = "orange")
```

Conclusion
=============================================================================
```{r}

```



